### ISSUE TITLE
为什么不做服务器端渲染

### ISSUE THREAD

**Issue by smalike** [bodyno/react-starter-kit#1]
为什么不做服务器端渲染，作者是考虑服务端渲染会有什么弊端所以没有做吗？

**Comment by bodyno** [comment]
对不起，很抱歉的告诉你，
为了保持项目的易扩展性，
本项目没有加入universal渲染，
各位可自行需要加入服务端渲染。

这里推荐下
https://github.com/erikras/react-redux-universal-hot-example
