### ISSUE TITLE
报错了，react应该选哪个版本安装？

### ISSUE THREAD

**Issue by vczhan** [bodyno/react-starter-kit#10]
> 273743 error Darwin 15.2.0
> 273744 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
> 273745 error node v4.4.5
> 273746 error npm  v2.14.7
> 273747 error code EPEERINVALID
> 273748 error peerinvalid The package react@15.2.0 does not satisfy its siblings' peerDependencies requirements!
> 273748 error peerinvalid Peer halogen@0.2.0 wants react@^0.14.8
> 273748 error peerinvalid Peer react-dom@15.2.0 wants react@^15.2.0
> 273748 error peerinvalid Peer react-redux@4.4.5 wants react@^0.14.0 || ^15.0.0-0
> 273748 error peerinvalid Peer react-router@2.5.2 wants react@^0.14.0 || ^15.0.0
> 273748 error peerinvalid Peer react-addons-test-utils@15.2.0 wants react@^15.2.0
> 273748 error peerinvalid Peer redbox-react@1.2.10 wants react@^0.14.0 || ^15.0.0
> 273748 error peerinvalid Peer enzyme@2.3.0 wants react@0.13.x || 0.14.x || ^15.0.0-0
> 273749 verbose exit [ 1, true ]

**Comment by bodyno** [comment]
不存在这问题
package.json 已经指定好react版本为15.0.0
正常安装下没有其它包的版本冲突
请再检查一下
