### ISSUE TITLE
sass 文件没有定位到具体行数

### ISSUE THREAD

**Issue by MinJieLiu** [bodyno/react-starter-kit#11]
sourceMap [定位都是第一行。这会给开发降低便捷性

![issure](https://minjieliu.github.io/assets/issures-image/1.png)

**Comment by bodyno** [comment]
@MinJieLiu 
sourceMap可以正确定位到文件
需要点击进入
可以看到
![123](https://cloud.githubusercontent.com/assets/5443058/16861143/987270fa-4a70-11e6-86e7-eaa4268df380.png)
