### ISSUE TITLE
bootstrap.js csss  jquery  

### ISSUE THREAD

**Issue by gischina** [bodyno/react-starter-kit#17]
bootstrap.js csss  jquery

**Comment by bodyno** [comment]
What do you mean?

**Comment by gischina** [comment]
index.html

**Comment by gischina** [comment]
<link rel="stylesheet" href="theme/bootstrap/css/bootstrap.min.css">

**Comment by gischina** [comment]
index.html   <link rel="stylesheet" href="theme/bootstrap/css/bootstrap.min.css">  or
<script src="theme/dist/js/app.min.js"></script>   but chrom GET http://localhost:3000/theme/bootstrap/css/bootstrap.min.css  404

**Comment by gischina** [comment]
index.html  ref  <link rel="stylesheet" href="theme/dist/css/AdminLTE.min.css">  or <script src="theme/dist/js/app.min.js"></script>  but  chrom GET http://localhost:3000/theme/dist/css/AdminLTE.min.css 404

**Comment by gischina** [comment]
index page references styles by link or reference js files via script,                                                             but after 3000 running GET http: // localhost: 3000 / theme / dist / css / AdminLTE.min.css 404                Thanks

**Comment by gischina** [comment]
index.html页面中我link和script很多第三方样式或脚本，但是运行起来之后chrom调试找不到这些样式或者脚本，用了webpack后就不能这样引用了吗，或者webpack要怎么配置才能引用这些，谢谢

**Comment by bodyno** [comment]
es6 需要使用import 导入各种js，css

**Comment by bodyno** [comment]
请先看看react的官方教程https://facebook.github.io/react/

**Comment by gischina** [comment]
1、
import '../../theme/bootstrap/css/bootstrap.min.css'
import '../../theme/dist/css/AdminLTE.min.css'
import '../../theme/dist/css/skins/skin-blue.min.css'
这些样式导入后 <header className="main-header">这种引用为什么没有作用
webpack是否需要配置

2、
import '../../theme/plugins/jQuery/jquery-2.2.3.min.js'
import '../../theme/bootstrap/js/bootstrap.min.js'
import '../../theme/dist/js/app.min.js'
这样引用也没有起作用，webpack是否需要配置

谢谢

**Comment by bodyno** [comment]
webpack 需要配置

**Comment by bodyno** [comment]
请看webpack文档
