### ISSUE TITLE
dist下的index.html文件不能直接打开吗

### ISSUE THREAD

**Issue by LeventZheng** [bodyno/react-starter-kit#21]
打开index.html文件会报错，提示是文件找不到；执行npm start后，打开文件会提示SecurityError: Failed to execute 'replaceState' on 'History': A history state object with URL 'file:///F:/404' cannot be created in a document with origin 'null' and URL 'file:///F:/library/react-starter-kit/dist/index.html'.

**Comment by bodyno** [comment]
直接运行会因为路径等不对导致找不到资源。
可以启动一个http服务器
或添加一个npm run prod 命令 与`npm start` 相同 只是NODE_ENV的值为 `production`

**Comment by LeventZheng** [comment]
部署到服务器上去的话，路径、端口号需要换吗

**Comment by bodyno** [comment]
这个根据你的需求

**Comment by LeventZheng** [comment]
部署到服务器上以后，怎么才能访问到入口文件呢

**Comment by LeventZheng** [comment]
服务端需要配置吗，还是像一般的html那样访问就可以了？

**Comment by bodyno** [comment]
用nxgin 指向dist下面的html就可以了 静态资源建议上传至CDN
