### ISSUE TITLE
babel-core没加到package.json里

### ISSUE THREAD

**Issue by bobby1991qw** [bodyno/react-starter-kit#22]
babel-core没加到package.json里

**Comment by bodyno** [comment]
@bobby1991qw 谢谢
已加入

**Comment by onweer** [comment]
ERROR in Cannot find module 'babel-core' 

还有一个地方 有一个变量是不是定义了没用？？
![image](https://cloud.githubusercontent.com/assets/11755669/19212034/e4a3de66-8d7b-11e6-8cc3-81f94e310ccd.png)

**Comment by bodyno** [comment]
@onweer 谢谢 已去掉
