### ISSUE TITLE
webpack-compiler Cannot find module 'babel-core'

### ISSUE THREAD

**Issue by hIvOv** [bodyno/react-starter-kit#24]
拉取项目之后,第一次 npm run compile 会报babel-core未安装的问题,你的package.json中没有加入babel-core的配置.报错如下:

to be executed: node bin/compile
  app:config Creating default configuration. +0ms
  app:config Looking for environment overrides for NODE_ENV "development". +3ms
  app:config Found overrides, applying to default configuration. +2ms
  app:webpack:config Creating configuration. +527ms
  app:webpack:config Enable plugins for live development (HMR, NoErrors). +1ms
  app:bin:compile Starting compiler. +67ms
  app:build:webpack-compiler Webpack compile completed. +1s
  app:build:webpack-compiler Hash: 5de5a013b9b8bb5b3621
Version: webpack 1.13.2
Time: 1070ms
                             Asset     Size  Chunks       Chunk Names
       app.5de5a013b9b8bb5b3621.js  80.4 kB       0       app
    vendor.5de5a013b9b8bb5b3621.js   386 kB       1       vendor
   app.5de5a013b9b8bb5b3621.js.map  88.6 kB       0       app
vendor.5de5a013b9b8bb5b3621.js.map   462 kB       1       vendor

ERROR in Cannot find module 'babel-core'
 @ multi app
Child html-webpack-plugin for "index.html":
         Asset    Size  Chunks       Chunk Names
    index.html  573 kB       0        +2ms
  app:build:webpack-compiler Webpack compiler encountered errors. +0ms
  app:build:webpack-compiler Cannot find module 'babel-core'

**Comment by bodyno** [comment]
已修复 谢谢！
