### ISSUE TITLE
Npm install Error

### ISSUE THREAD

**Issue by superchangme** [bodyno/react-starter-kit#25]
When i run npm install, It occurs error as below

npm ERR! peerinvalid The package react@15.3.2 does not satisfy its siblings' pee
## rDependencies requirements!

![image](https://cloud.githubusercontent.com/assets/7008154/19334861/98414a22-9131-11e6-8ddd-70000fac6634.png)

**Comment by bodyno** [comment]
If your network access npm is not good enough. 

You can use [cnpm](https://github.com/cnpm/cnpm) to download npm package well.

**Comment by superchangme** [comment]
Thanks ,it fixed.
