### ISSUE TITLE
你上次提交改错了

### ISSUE THREAD

**Issue by lileilei** [bodyno/react-starter-kit#28]
我专门查看了一下老外的用的也是OccurrenceOrderPlugin
new webpack.optimize.OccurrenceOrderPlugin(preferEntry)   确实这么写的。http://webpack.github.io/docs/list-of-plugins.html#occurrenceorderplugin  官网上也是这么写的。可能是更新了我也很奇怪

**Comment by bodyno** [comment]
的确是OccurrenceOrderPlugin
感谢指出
