### ISSUE TITLE
the hot replace is not valid in server static file

### ISSUE THREAD

**Issue by superchangme** [bodyno/react-starter-kit#29]
When i use custom index.html in iis file,js bundle file is not changed when i modify the code.
Here is my html file

```
![image](https://cloud.githubusercontent.com/assets/7008154/19640471/69742502-9a0f-11e6-8c9f-bc09528f9cfa.png)

```

![image](https://cloud.githubusercontent.com/assets/7008154/19640439/412362fc-9a0f-11e6-9253-6a6c14fb5a29.png)
There sth. broken ,Can you give a suggestion?

**Comment by bodyno** [comment]
it's because that mabe you IP address is broken.
Try `npm start` again. It will be ok
