### ISSUE TITLE
给RouteIndex加action

### ISSUE THREAD

**Issue by HuaRongSAO** [bodyno/react-starter-kit#31]
我如何用符合规范（component,containers,modules）的方式去链接indexRoute：Home，添加其他的事件

**Comment by bodyno** [comment]
一样的
建立文件夹
在store/redurcer.js 中把全局reducer引入进来就可以了

**Comment by HuaRongSAO** [comment]
麻烦了，我是刚刚接触不久。问题还是有的store获取不到，dispatch未定义。
route/index.js
`
export const createRoutes = (store) => ({
  path: '/',
  component: CoreLayout,
  indexRoute: Home,//  HomeView 组件
  childRoutes: [
    ArticleRoute(store),
    CategoriesRoute(store),
    ArchivesRoute(store),
    TagsRoute(store),
    AboutRoute(store),
    ListViewRoute(store),
    PageNotFound(),
    Redirect
  ]
})`

route/HomeView/index.js
`export default {
  component: HomeView,
  // 使用 getIndexRoute，getComponent 貌似并没有被运行
  // getIndexRoute(nextState, cb) {
  //   require.ensure([], (require) => {
  //     const Home = require('./containers/HomeContainers').default
  //     const reducer = require('./modules/HomeModules').default
  //     injectReducer(store, { key: 'home', reducer })
  //     cb(null, Home)
  //   })
  // },
  // getComponent (nextState, cb) {
  //   require.ensure([], (require) => {
  //     const Home = require('./containers/HomeContainers').default
  //     const reducer = require('./modules/HomeModules').default
  //     injectReducer(store, { key: 'home', reducer })
  //     cb(null, Home)
  //   })
  // }
}`



route/HomeView/components/HomeView.js
`import React, {Component} from 'react'
import {bindActionCreators} from 'redux'
import {connect} from 'react-redux'
import {injectReducer} from './../../../store/reducers'


export class HomeView extends Component {
  render() {
    const {store} = this.props //store undefined
    return (
      <div>
        {console.log(this.props)}
        <h1>Hello World</h1>
      </div>
    )
  }
}
// 就是这边injectReducer 如何用 ？
const HomeContainers = require('./../containers/HomeContainers').default
const reducer = require('./../modules/HomeModules').default

export default injectReducer(store, {key: 'home', reducer})
)
`
//++++++问题应该师出在这两个文件，但是我试了很久还是不懂。或者 能不能推荐个相关框架开发的开源项目。谢谢了

**Comment by HuaRongSAO** [comment]
麻烦了，我是刚刚接触不久。问题还是有的store获取不到，dispatch未定义。
route/index.js
`
export const createRoutes = (store) => ({

  path: '/',

  component: CoreLayout,

  indexRoute: Home,//HomeView 组件

  childRoutes: [

```
CounterRoute(store),

ZenRoute(store),
```

  ]
})
`

route/HomeView/index.js
`
import HomeView from './components/HomeView'

// Sync route definition
export default {
  component: HomeView,

  // 使用 getIndexRoute，getComponent 貌似并没有被运行
  // getIndexRoute(nextState, cb) {
  //   require.ensure([], (require) => {
  //     const Home = require('./containers/HomeContainers').default
  //     const reducer = require('./modules/HomeModules').default
  //     injectReducer(store, { key: 'home', reducer })
  //     cb(null, Home)
  //   })
  // },
  // getComponent (nextState, cb) {
  //   require.ensure([], (require) => {
  //     const Home = require('./containers/HomeContainers').default
  //     const reducer = require('./modules/HomeModules').default
  //     injectReducer(store, { key: 'home', reducer })
  //     cb(null, Home)
  //   })
  // }
}
`

route/HomeView/components/HomeView.js
`
import React, {Component} from 'react'
import {bindActionCreators} from 'redux'
import {connect} from 'react-redux'
import {injectReducer} from './../../../store/reducers'

export class HomeView extends Component {
  render() {
    const {store} = this.props   //  ====store undefined
    return (
      <div>
        {console.log(this.props)}
      </div>
    )
  }
}

const HomeContainers = require('./../containers/HomeContainers').default
const reducer = require('./../modules/HomeModules').default

export default injectReducer(store, {key: 'home', reducer})

`
//++++++问题应该师出在这两个文件，但是我试了很久还是不懂。或者 能不能推荐个相关框架开发的开源项目。谢谢了

**Comment by bodyno** [comment]
可以参考一下官方文档
