### ISSUE TITLE
执行npm run deploy:prod报错

### ISSUE THREAD

**Issue by j306796405** [bodyno/react-starter-kit#36]
Executing script: compile

to be executed: node bin/compile 
  app:config Creating default configuration. +0ms
  app:config Looking for environment overrides for NODE_ENV "production". +4ms
  app:config Found overrides, applying to default configuration. +2ms
  app:webpack:config Creating configuration. +511ms
  app:webpack:config Enable plugins for production (OccurenceOrder, Dedupe & UglifyJS). +1ms
  app:webpack:config Apply ExtractTextPlugin to CSS loaders. +93ms
  app:bin:compile Starting compiler. +2ms
  app:bin:compile Compiler encountered an error. TypeError: arguments[i].apply is not a function
    at Compiler.apply (/Users/jeffery/work/marketing-system/node_modules/.0.1.10@tapable/lib/Tapable.js:164:16)
    at OptionsApply.WebpackOptionsApply.process (/Users/jeffery/work/marketing-system/node_modules/.1.14.0@webpack/lib/WebpackOptionsApply.js:62:18)
    at webpack (/Users/jeffery/work/marketing-system/node_modules/.1.14.0@webpack/lib/webpack.js:22:48)
    at Promise (/Users/jeffery/work/marketing-system/build/webpack-compiler.js:9:22)
    at webpackCompiler (/Users/jeffery/work/marketing-system/build/webpack-compiler.js:8:10)
    at Promise.resolve.then (/Users/jeffery/work/marketing-system/bin/compile.js:12:17)
    at process._tickCallback (internal/process/next_tick.js:103:7)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3 +8ms

npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "compile"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! react-starter-kit@0.2.0 compile: `better-npm-run compile`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-starter-kit@0.2.0 compile script 'better-npm-run compile'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-starter-kit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     better-npm-run compile
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-starter-kit
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-starter-kit
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jeffery/work/marketing-system/npm-debug.log

npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "deploy"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! react-starter-kit@0.2.0 deploy: `better-npm-run deploy`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-starter-kit@0.2.0 deploy script 'better-npm-run deploy'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-starter-kit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     better-npm-run deploy
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-starter-kit
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-starter-kit
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jeffery/work/marketing-system/npm-debug.log

npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "deploy:prod"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! react-starter-kit@0.2.0 deploy:prod: `better-npm-run deploy:prod`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-starter-kit@0.2.0 deploy:prod script 'better-npm-run deploy:prod'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-starter-kit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     better-npm-run deploy:prod
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-starter-kit
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-starter-kit
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jeffery/work/marketing-system/npm-debug.log

**Comment by bodyno** [comment]
If you are in China.
Install package use (cnpm)[https://npm.taobao.org/].

**Comment by bodyno** [comment]
If you are in China.
Please use [cnpm](https://npm.taobao.org/) install package.

**Comment by j306796405** [comment]
@bodyno 还是不行  😩

**Comment by bodyno** [comment]
@j306796405 可以的 你把目录删了 再安装下

**Comment by j306796405** [comment]
@bodyno 谢谢 可以关了 我自己webpackConfig.plugins配置错了

**Comment by bodyno** [comment]
👍 👍 👍
