### ISSUE TITLE
请教一个进入url取数据的问题

### ISSUE THREAD

**Issue by JamesYuan** [bodyno/react-starter-kit#39]
请问，如何在进入react-router onEnter (??) 的时候，就已经从服务器（https://api.github.com/zen）取得了一次初始数据并显示在页面中呢？

https://github.com/bodyno/react-starter-kit/tree/master/src/routes/Zen

Thanks,
James

**Comment by bodyno** [comment]
很简单

onEnter 方法中有3个参数`nextState, replace, next`

等取完数据后再调用`next()`方法即可

**Comment by JamesYuan** [comment]
is this correct?

export default (store) => ({
  path: 'zen',
  getComponent (nextState, cb) {
    require.ensure([], (require) => {
      const Zen = require('./containers/ZenContainer').default
      const reducer = require('./modules/zen').default
      injectReducer(store, { key: 'zen', reducer })
      cb(null, Zen)
    })
  },
  onEnter: (nextState, replace, next)=>{
    fetch('https://api.github.com/zen')
      .then(data => data.text())
      .then(text => {store.dispatch({
          type: 'RECEIVE_ZEN',
          payload: {
            text: text,
            id: 0
          }
        }
      );
        next();
      })
      .catch(error => {
        // do some error handling here
        next(error);
      })
  }
})

**Comment by bodyno** [comment]
You can run it.
If correct is right then right.

**Comment by JamesYuan** [comment]
thanks.
