### ISSUE TITLE
请教一个Webpack CSS

### ISSUE THREAD

**Issue by JamesYuan** [bodyno/react-starter-kit#42]
Hi,

我在src/styles/_base.scss中引用了此其它的css, 比如

@import 'components.min.css';
@import 'plugins.min.css';
@import 'layout.min.css';
@import 'theme.css';
@import 'custom.css';

但是，这引起css引入了一些image的图片，而我的image是不全的，会引起以下的错误：

ERROR in ./~/css-loader?sourceMap&-minimize!./src/styles/layout.min.css
Module not found: Error: Cannot resolve 'file' or 'directory' ../img/icon-color.png in /Users/projects/react/kejibd/tl_web_ui/src/styles
 @ ./~/css-loader?sourceMap&-minimize!./src/styles/layout.min.css 6:57774-57806 6:60292-60324

ERROR in ./~/css-loader?sourceMap&-minimize!./src/styles/layout.min.css
Module not found: Error: Cannot resolve 'file' or 'directory' ../img/icon-color-close.png in /Users/projects/react/kejibd/tl_web_ui/src/styles
 @ ./~/css-loader?sourceMap&-minimize!./src/styles/layout.min.css 6:58016-58054

请问如何才能忽略这种错误？

Thanks,
james.

**Comment by bodyno** [comment]
图片必须要有 不然会报错

**Comment by JamesYuan** [comment]
有没有webpack loader之类的可以忽略掉错误呢？

**Comment by bodyno** [comment]
你可以自己写一个 很简单的

**Comment by JamesYuan** [comment]
got it, thanks.
