### ISSUE TITLE
npm run dev command can not be used

### ISSUE THREAD

**Issue by liadbiz** [bodyno/react-starter-kit#46]
when I run npm run dev
here is the message:

react-starter-kit@0.2.0 dev /home/liadbiz/learning/learn-react/react-starter-kit
better-npm-run dev

running better-npm-run in /home/liadbiz/learning/learn-react/react-starter-kit
Executing script: dev

to be executed: nodemon --exec node bin/server --ignore dist --ignore coverage --ignore tests --ignore src 
  Usage: nodemon [nodemon options] [script.js] [args]

  See "nodemon --help" for more.

so, I gusse it's a problem about nodemon. and then I change the dev script to this way:

>  "command": "nodemon bin/server --ignore dist --ignore coverage --ignore tests --ignore src",
 then every thing works fine.

Is this a issue in this repo?

**Comment by bodyno** [comment]
#47 
fixed
Thanks for PR
