### ISSUE TITLE
请问怎么安装  decorator编译语法

### ISSUE THREAD

**Issue by a709691139** [bodyno/react-starter-kit#48]
我安装了babel-plugin-transform-decorators， 还有修改 .babelrc 添加plugins，
还是有报错

Decorators are not officially supported yet in 6.x pending a proposal update.
However, if you need to use them you can install the legacy decorators transform with:

npm install babel-plugin-transform-decorators-legacy --save-dev

and add the following line to your .babelrc file:

{
  "plugins": ["transform-decorators-legacy"]
}

The repo url is: https://github.com/loganfsmyth/babel-plugin-transform-decorators-legacy.
  13 |
  14 | @observer
> 15 | class Counter extends Component{
     | ^

**Comment by a709691139** [comment]
好了，解决了，还要在 plugins里面加上decorators
compiler_babel : {
    cacheDirectory : true,
    plugins        : ['transform-runtime','babel-plugin-transform-decorators-legacy'],
    presets        : ['es2015', 'react', 'stage-0']
  },

**Comment by bodyno** [comment]
👍
