### ISSUE TITLE
win10 下 npm install 失败 报错

### ISSUE THREAD

**Issue by soojade** [bodyno/react-starter-kit#5]
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "D:\program\nodejs\node.exe" "D:\program\nodejs\node_modules\npm\bin\npm-cli.js" "i"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE

npm ERR! phantomjs-prebuilt@2.1.7 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs-prebuilt@2.1.7 install script 'node install.js'.

**Comment by bodyno** [comment]
phantomjs 安装失败了
把node_modules目录删了
重新再安装一次
如果还是不行
请用vpn
