### ISSUE TITLE
node-sass必须安装吗？

### ISSUE THREAD

**Issue by cycorey** [bodyno/react-starter-kit#6]
这样的话，本地没有安装过visual studio的同事，npm install 都过不去。

能否考虑把部分需要native编译的东西，把编译结果也发布一下？

非常好的脚手架项目，谢谢！

**Comment by bodyno** [comment]
node-sass 是在依赖项里面的
不一定需要visual studio才可以安装通过
windows下面有时候会有点报错
但是不是很影响 项目还是可以跑起来
:smile:

**Comment by cycorey** [comment]
我这里运行 npm start 会提示以下报错：

ERROR in Cannot find module 'node-sass'
 @ ./src/layouts/CoreLayout/CoreLayout.scss 4:14-284 13:2-17:4 14:20-290

ERROR in Cannot find module 'node-sass'
 @ ./src/styles/core.scss 4:14-269 13:2-17:4 14:20-275

ERROR in Cannot find module 'node-sass'
 @ ./src/routes/Home/components/HomeView.scss 4:14-291 13:2-17:4 14:20-297

ERROR in Cannot find module 'node-sass'
 @ ./src/routes/Zen/components/Zen.scss 4:14-286 13:2-17:4 14:20-292

ERROR in Cannot find module 'node-sass'
 @ ./src/components/Header/Header.scss 4:14-280 13:2-17:4 14:20-286

ERROR in Cannot find module 'node-sass'
 @ ./src/routes/Form/components/Form.scss 4:14-287 13:2-17:4 14:20-293

ERROR in Cannot find module 'node-sass'
 @ ./src/components/Counter/Counter.scss 4:14-281 13:2-17:4 14:20-287
Child html-webpack-plugin for "index.html":
         Asset    Size  Chunks       Chunk Names
    index.html  553 kB       0
webpack: bundle is now VALID.

**Comment by cycorey** [comment]
请问node-sass 不需要 visual studio 的话，在windows下怎样才能安装上呢？

**Comment by bodyno** [comment]
node-sass 主要依赖这个库
https://github.com/nodejs/node-gyp
可以尝试先把这个库安装好 就行了

**Comment by cycorey** [comment]
谢谢，已通过！
