### ISSUE TITLE
ERROR in ENOENT: no such file or directory, scandir 

### ISSUE THREAD

**Issue by believeZJP** [bodyno/react-starter-kit#60]
![image](https://cloud.githubusercontent.com/assets/15198091/24485662/7f40da98-1538-11e7-87b1-9e2bf18dff9a.png)
安装都ok了，npm start 报这个错，怎么解？

**Comment by bodyno** [comment]
请重新检查一下包是否都安装成功了
建议删除到目录，重新安装一遍
