### ISSUE TITLE
当我尝试修改代码之后，遇到个问题

### ISSUE THREAD

**Issue by renlindong** [bodyno/react-starter-kit#64]
![image](https://cloud.githubusercontent.com/assets/20882991/25795122/83ac436e-3406-11e7-9047-c145d109dbed.png)
怎么解决这个问题呢

**Comment by bodyno** [comment]
跨域了
你可以把environments.js
`compiler_public_path`改为`/`

**Comment by renlindong** [comment]
谢谢！解决了！
