### ISSUE TITLE
项目如何部署到静态资源服务器上？

### ISSUE THREAD

**Issue by ajnudnyy** [bodyno/react-starter-kit#65]
项目打完包之后，压缩后的代码可以直接copy到如nginx的资源服务器上运行访问吗？

**Comment by bodyno** [comment]
可以，参照https://github.com/ReactTraining/react-router/blob/v3/docs/guides/Histories.md#configuring-your-server

**Comment by ajnudnyy** [comment]
谢谢大哥回复，但是具体是改哪个文件的路由啊？ 求求各位了， 都快一年了，我就一个人研究react，所有的问题我自己都解决了，就这一个问题，能不能稍微来一丁点详细的， 这个链接我看过好多次了，看不明白是干嘛的，

**Comment by ajnudnyy** [comment]
谢谢大哥回复，但是具体是改哪个文件的路由啊？ 求求各位了， 都快一年了，我就一个人研究react，所有的问题我自己都解决了，就这一个问题，能不能稍微来一丁点详细的， 这个链接我看过好多次了，看不明白是干嘛的， react我都做好几个了，就卡在这个点上

**Comment by ajnudnyy** [comment]
跪求细解， 或者详细配置文档

**Comment by ajnudnyy** [comment]
谢谢大哥

**Comment by Hydraz320** [comment]
发布到线上并不是复制过去的……比方说会有路径问题 发布到线上有很多东西可以搜搜的
大佬是怎么玩的Nginx呀 我还没有玩过

**Comment by bodyno** [comment]
目前是打包时自动将文件上传至oss
然后指定compiler_public_path为oss的路径
这样做是比较方便的

**Comment by bodyno** [comment]
目前是打包时自动将文件上传至oss
然后指定compiler_public_path为oss的路径
这样做是比较方便的
