### ISSUE TITLE
有个问题,热加载后,浏览器没更新

### ISSUE THREAD

**Issue by kkstun** [bodyno/react-starter-kit#67]
我修改了js文件, webpack: Compiled successfully.
但是浏览器并没有更新?    我之前用的是vue

**Comment by zed31124** [comment]
我猜你是因为跨域了吧
![Uploading F281D0D5-CE39-4627-80E8-7C141C95A71A.png…]()

**Comment by zed31124** [comment]
上次我遇到了同样的问题，控制台显示跨域了，你的应该也是这个问题。

**Comment by renlindong** [comment]
上次我遇到同样的问题，log显示跨域了，你应该也是一样的问题。你可以把environments.js
compiler_public_path改为/

**Comment by bodyno** [comment]
👍 👍 👍

**Comment by kkstun** [comment]
确实是这样的.多谢指点
