### ISSUE TITLE
反应一个bug

### ISSUE THREAD

**Issue by renlindong** [bodyno/react-starter-kit#68]
我npm run deploy:prod之后，一切正常，没有报错。当我尝试打开/dist/indx.html之后，log报错
![e1ba664c-47e6-413d-98ec-8a66eaf74550](https://cloud.githubusercontent.com/assets/20882991/26121590/615c1a1c-3aa7-11e7-8bee-8c8c23470ff7.png)
原index.html内容如下
![f1f923a1-f2b4-4db9-bdff-f49002fd5d11](https://cloud.githubusercontent.com/assets/20882991/26121739/d56968e2-3aa7-11e7-94ec-fa8891f38b97.png)
然后我尝试修改了index.html
![8458ae68-4897-4819-bbd2-d0ab9f63252c](https://cloud.githubusercontent.com/assets/20882991/26121785/f8eb1680-3aa7-11e7-9e19-3f105571d397.png)
之后界面出来了，但是当我切换路由的时候，又遇到了一个新的问题
![a3a552db-f55c-4e6a-b01c-6485379520a4](https://cloud.githubusercontent.com/assets/20882991/26121858/3383425e-3aa8-11e7-8a67-1ae3e95d8f0d.png)
应该都是同样的问题，所以我vendor.xxx.js中找到e.p="/"，将其改为e.p="./"。这样就解决了。

**Comment by bodyno** [comment]
可以在webpack中设置
一般设成`/`是用于把文件部署在根服务器上用的

**Comment by renlindong** [comment]
原来是这样啊。。
