### ISSUE TITLE
报以下错误，发现node_modules\node-sass\vendor 不存在

### ISSUE THREAD

**Issue by cycorey** [bodyno/react-starter-kit#7]
npm install不再报错了，但是执行 npm start报以下错误，求助，谢谢！

`> npm start

> react-starter-kit@1.0.0 start C:\cy\npm\react-starter-kit-master\react-starter-kit-master
> better-npm-run start

running better-npm-run in C:\cy\npm\react-starter-kit-master\react-starter-kit-master
Executing script: start

to be executed: "babel-node bin/server"
  app:config Creating default configuration. +0ms
  app:config Looking for environment overrides for NODE_ENV "development". +46ms
  app:config Found overrides, applying to default configuration. +20ms
  app:webpack:config Create configuration. +2s
  app:webpack:config Enable plugins for live development (HMR, NoErrors). +7ms
  app:server:webpack-dev Enable webpack dev middleware. +733ms
  app:server:webpack-hmr Enable Webpack Hot Module Replacement (HMR). +85ms
  app:bin:server Server is now running at http://localhost:3000. +11ms
webpack built bb9ea20edf50c434d669 in 5950ms
Hash: bb9ea20edf50c434d669
Version: webpack 1.13.1
Time: 5950ms
                                Asset     Size  Chunks       Chunk Names
       vendor.bb9ea20edf50c434d669.js   392 kB       6       vendor
 f59f4511d84f12ab97492b43febf6636.jpg  39.6 kB
    1.counter.bb9ea20edf50c434d669.js  29.8 kB       1       counter
        2.zen.bb9ea20edf50c434d669.js  36.7 kB       2       zen
     3.elapse.bb9ea20edf50c434d669.js   4.7 kB       3       elapse
       4.form.bb9ea20edf50c434d669.js  30.4 kB       4       form
      5.route.bb9ea20edf50c434d669.js  4.22 kB       5       route
          app.bb9ea20edf50c434d669.js  1.01 MB       0       app
      app.bb9ea20edf50c434d669.js.map  1.22 MB       0       app
1.counter.bb9ea20edf50c434d669.js.map  35.8 kB       1       counter
    2.zen.bb9ea20edf50c434d669.js.map  44.4 kB       2       zen
 3.elapse.bb9ea20edf50c434d669.js.map  4.01 kB       3       elapse
   4.form.bb9ea20edf50c434d669.js.map    36 kB       4       form
  5.route.bb9ea20edf50c434d669.js.map  3.13 kB       5       route
   vendor.bb9ea20edf50c434d669.js.map   471 kB       6       vendor

ERROR in ENOENT: no such file or directory, scandir 'C:\cy\npm\react-starter-kit-master\react-starter-kit-master\node_modules\node-sass\vendor'
 @ ./src/layouts/CoreLayout/CoreLayout.scss 4:14-284 13:2-17:4 14:20-290

ERROR in ENOENT: no such file or directory, scandir 'C:\cy\npm\react-starter-kit-master\react-starter-kit-master\node_modules\node-sass\vendor'
 @ ./src/styles/core.scss 4:14-269 13:2-17:4 14:20-275

ERROR in ENOENT: no such file or directory, scandir 'C:\cy\npm\react-starter-kit-master\react-starter-kit-master\node_modules\node-sass\vendor'
 @ ./src/routes/Home/components/HomeView.scss 4:14-291 13:2-17:4 14:20-297

ERROR in ENOENT: no such file or directory, scandir 'C:\cy\npm\react-starter-kit-master\react-starter-kit-master\node_modules\node-sass\vendor'
 @ ./src/routes/Form/components/Form.scss 4:14-287 13:2-17:4 14:20-293

ERROR in ENOENT: no such file or directory, scandir 'C:\cy\npm\react-starter-kit-master\react-starter-kit-master\node_modules\node-sass\vendor'
 @ ./src/routes/Zen/components/Zen.scss 4:14-286 13:2-17:4 14:20-292

ERROR in ENOENT: no such file or directory, scandir 'C:\cy\npm\react-starter-kit-master\react-starter-kit-master\node_modules\node-sass\vendor'
 @ ./src/components/Header/Header.scss 4:14-280 13:2-17:4 14:20-286

ERROR in ENOENT: no such file or directory, scandir 'C:\cy\npm\react-starter-kit-master\react-starter-kit-master\node_modules\node-sass\vendor'
 @ ./src/components/Counter/Counter.scss 4:14-281 13:2-17:4 14:20-287
Child html-webpack-plugin for "index.html":
         Asset    Size  Chunks       Chunk Names
    index.html  553 kB       0
webpack: bundle is now VALID.`

**Comment by cycorey** [comment]
npm rebuild node-sass 就解决所有问题了【需要安装visual studio 2015，并 执行 npm config set msvs_version 2015】

**Comment by liuyongfei1** [comment]
It works for me! @cycorey

**Comment by PaulWangCN** [comment]
thx, it solutes my trouble. @cycorey
