### ISSUE TITLE
亲，我想用这个项目作为我们公司前段页面的架构

### ISSUE THREAD

**Issue by ajnudnyy** [bodyno/react-starter-kit#76]
我想在这个项目的基础上做我们公司项目的开发， 但是下载下来不能更换目录， 请问是否需要获得license，在可以在本机以至于拷贝到其他同事电脑上互相拷贝？

**Comment by bodyno** [comment]
可以更换目录 就和你本地文件一样 想干啥干啥
license是Do What The F*ck You Want To Public License
