### ISSUE TITLE
npm run compile 错误

### ISSUE THREAD

**Issue by tanyun1111** [bodyno/react-starter-kit#9]
ERROR in ENOENT: no such file or directory, scandir 'D:\workspace\nwjs\react-sta
rter-kit\node_modules\node-sass\vendor'
 @ ./src/layouts/CoreLayout/CoreLayout.scss 4:14-284 13:2-17:4 14:20-290

ERROR in ENOENT: no such file or directory, scandir 'D:\workspace\nwjs\react-sta
rter-kit\node_modules\node-sass\vendor'
 @ ./src/styles/core.scss 4:14-269 13:2-17:4 14:20-275

ERROR in ENOENT: no such file or directory, scandir 'D:\workspace\nwjs\react-sta
rter-kit\node_modules\node-sass\vendor'
 @ ./src/routes/Home/components/HomeView.scss 4:14-291 13:2-17:4 14:20-297

ERROR in ENOENT: no such file or directory, scandir 'D:\workspace\nwjs\react-sta
rter-kit\node_modules\node-sass\vendor'
 @ ./src/routes/PageNotFound/components/PageNotFound.scss 4:14-295 13:2-17:4 14:
20-301

ERROR in ENOENT: no such file or directory, scandir 'D:\workspace\nwjs\react-sta
rter-kit\node_modules\node-sass\vendor'
 @ ./src/routes/Form/components/Form.scss 4:14-287 13:2-17:4 14:20-293

ERROR in ENOENT: no such file or directory, scandir 'D:\workspace\nwjs\react-sta
rter-kit\node_modules\node-sass\vendor'
 @ ./src/routes/Zen/components/Zen.scss 4:14-286 13:2-17:4 14:20-292

ERROR in ENOENT: no such file or directory, scandir 'D:\workspace\nwjs\react-sta
rter-kit\node_modules\node-sass\vendor'
 @ ./src/components/Header/Header.scss 4:14-280 13:2-17:4 14:20-286

ERROR in ENOENT: no such file or directory, scandir 'D:\workspace\nwjs\react-sta
rter-kit\node_modules\node-sass\vendor'
 @ ./src/components/Counter/Counter.scss 4:14-281 13:2-17:4 14:20-287
Child html-webpack-plugin for "index.html":
         Asset    Size  Chunks       Chunk Names
    index.html  553 kB       0        +6ms
  app:build:webpack-compiler Webpack compiler encountered errors. +103ms
  app:build:webpack-compiler ENOENT: no such file or directory, scandir 'D:\work
space\nwjs\react-starter-kit\node_modules\node-sass\vendor'
 @ ./src/layouts/CoreLayout/CoreLayout.scss 4:14-284 13:2-17:4 14:20-290
ENOENT: no such file or directory, scandir 'D:\workspace\nwjs\react-starter-kit\
node_modules\node-sass\vendor'
 @ ./src/styles/core.scss 4:14-269 13:2-17:4 14:20-275
ENOENT: no such file or directory, scandir 'D:\workspace\nwjs\react-starter-kit\
node_modules\node-sass\vendor'
 @ ./src/routes/Home/components/HomeView.scss 4:14-291 13:2-17:4 14:20-297
ENOENT: no such file or directory, scandir 'D:\workspace\nwjs\react-starter-kit\
node_modules\node-sass\vendor'
 @ ./src/routes/PageNotFound/components/PageNotFound.scss 4:14-295 13:2-17:4 14:
20-301
ENOENT: no such file or directory, scandir 'D:\workspace\nwjs\react-starter-kit\
node_modules\node-sass\vendor'
 @ ./src/routes/Form/components/Form.scss 4:14-287 13:2-17:4 14:20-293
ENOENT: no such file or directory, scandir 'D:\workspace\nwjs\react-starter-kit\
node_modules\node-sass\vendor'
 @ ./src/routes/Zen/components/Zen.scss 4:14-286 13:2-17:4 14:20-292
ENOENT: no such file or directory, scandir 'D:\workspace\nwjs\react-starter-kit\
node_modules\node-sass\vendor'
 @ ./src/components/Header/Header.scss 4:14-280 13:2-17:4 14:20-286
ENOENT: no such file or directory, scandir 'D:\workspace\nwjs\react-starter-kit\
node_modules\node-sass\vendor'
 @ ./src/components/Counter/Counter.scss 4:14-281 13:2-17:4 14:20-287 +2ms
  app:bin:compile Compiler encountered an error. +13ms Error: Webpack compiler e
ncountered errors
    at webpack-compiler.js:24:23
    at Compiler.<anonymous> (D:\workspace\nwjs\react-starter-kit\node_modules\we
bpack\lib\Compiler.js:181:13)
    at D:\workspace\nwjs\react-starter-kit\node_modules\webpack\lib\Compiler.js:
403:12
    at Compiler.next (D:\workspace\nwjs\react-starter-kit\node_modules\tapable\l
ib\Tapable.js:67:11)
    at Compiler.<anonymous> (D:\workspace\nwjs\react-starter-kit\node_modules\we
bpack\lib\CachePlugin.js:40:4)
    at Compiler.applyPluginsAsync (D:\workspace\nwjs\react-starter-kit\node_modu
les\tapable\lib\Tapable.js:71:13)
    at Compiler.<anonymous> (D:\workspace\nwjs\react-starter-kit\node_modules\we
bpack\lib\Compiler.js:400:9)
    at Compilation.<anonymous> (D:\workspace\nwjs\react-starter-kit\node_modules
\webpack\lib\Compilation.js:577:13)
    at Compilation.applyPluginsAsync (D:\workspace\nwjs\react-starter-kit\node_m
odules\tapable\lib\Tapable.js:60:69)
    at Compilation.<anonymous> (D:\workspace\nwjs\react-starter-kit\node_modules
\webpack\lib\Compilation.js:572:10)
    at Compilation.applyPluginsAsync (D:\workspace\nwjs\react-starter-kit\node_m
odules\tapable\lib\Tapable.js:60:69)
    at Compilation.<anonymous> (D:\workspace\nwjs\react-starter-kit\node_modules
\webpack\lib\Compilation.js:567:9)
    at Compilation.applyPluginsAsync (D:\workspace\nwjs\react-starter-kit\node_m
odules\tapable\lib\Tapable.js:60:69)
    at Compilation.<anonymous> (D:\workspace\nwjs\react-starter-kit\node_modules
\webpack\lib\Compilation.js:563:8)
    at Compilation.applyPluginsAsync (D:\workspace\nwjs\react-starter-kit\node_m
odules\tapable\lib\Tapable.js:60:69)
    at Compilation.seal (D:\workspace\nwjs\react-starter-kit\node_modules\webpac
k\lib\Compilation.js:525:7)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\Program Files\nodejs\node.exe" "D:\Program Files\nodejs\
node_modules\npm\bin\npm-cli.js" "run" "compile"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! code ELIFECYCLE
npm ERR! react-starter-kit@1.0.0 compile: `better-npm-run compile`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-starter-kit@1.0.0 compile script 'better-npm-run co
mpile'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-starter-kit pac
kage,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     better-npm-run compile
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-starter-kit
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-starter-kit
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\workspace\nwjs\react-starter-kit\npm-debug.log

**Comment by bodyno** [comment]
更新了一下，
可以拉下最新的代码运行下，
应该是环境问题
